@startuml
'https://plantuml.com/class-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold

hide empty members

class Java2Puml{

}

class ToolProvider{
    name
    run
}

class ClassLoader

class Objects

class PrintWriter{
    autoFlush
}

Java2Puml - ToolProvider
ToolProvider -- Objects
ToolProvider -- ClassLoader
ToolProvider -- PrintWriter

@enduml