@startuml
'https://plantuml.com/sequence-diagram
skinparam style strictuml
hide footbox

participant Java2Puml
participant PumlDoclet
participant PumlDiagram
participant ClassContent
participant Attribut
participant Methode
participant Liaison

[o-> Java2Puml ++ : main(args)
Java2Puml -> PumlDoclet ++ : run(System.out, System.err, args)
    PumlDoclet -->> PumlDiagram ** : <<create>> PumlDiagram(name : String, directory : String, docletEnvironment : DocletEnvironment)
    PumlDoclet -> PumlDiagram ++ : chercherClasses()
        loop element : Element
            PumlDiagram -> ClassContent ** : <<create>> ClassContent()
            PumlDiagram -> ClassContent ++ : setClass(element : Element)
                loop enclosedElement : Element
                    ClassContent -->> Attribut ** : <<create>> Attribut(enclosedElement : Element)
                    ClassContent -->> Methode ** : <<create>> Methode(enclosedElement : Element)
                end
            return setClass()
        end
    return chercherClasses()

    PumlDoclet -> PumlDiagram ++ : chercherLiaisons()
        loop element : Element
            loop elementCompar : Element
                alt elementCompar is superclass of element
                    PumlDiagram -->> Liaison ** : <<create>> Liaison(element1 : ClassContent, element2 : ClassContent, typeLiaison : TypeLiaison)
                end
            end
            loop enclosedElement : Element
                alt enclosedElement is Field
                    PumlDiagram -->> Liaison ** : <<create>> Liaison(element1 : ClassContent, element2 : ClassContent, typeLiaison : TypeLiaison)
                end
            end
            loop enclosedElement : Element
                alt enclosedElement is Interface
                    PumlDiagram -->> Liaison ** : <<create>> Liaison(element1 : ClassContent, element2 : ClassContent, typeLiaison : TypeLiaison)
                end
            end
        end
    return chercherLiaisons()

    PumlDoclet -> PumlDiagram ++ : genererDiagramme()
        PumlDiagram -> PumlDiagram : createFile()
        loop classContent : ClassContent
            PumlDiagram -> ClassContent ++ : genererContenuClasse(element : Element)
            return genererContenuClasse() : String
        end
        loop liaison : Liaison
            PumlDiagram -> Liaison ++ : genererLiaison(liaison)
            return genererLiaison() : String
        end
        PumlDiagram -> PumlDiagram : endFile()
    return genererDiagramme()
return run() = true

@enduml