@startuml
'https://plantuml.com/class-diagram

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold

hide empty members

class Java2Puml{
}
class PumlDoclet{
    - name : String
    - directory : String
}
class PumlDiagram{
    - name : String
    - directory : String
}
class ClassContent{
    - className : String
}
class Attribut{
    - nom : String
    - type : PrimitiveType
}
class Methode{
    - nom : String
}
class Liaison{
}
enum TypeLiaison <<enum>>{
    HERITAGE
    SIMPLE
    IMPLEMENT
    AGREGATION
    COMPOSITION
}
enum Visibilite <<enum>>{
    PUBLIC
    PROTECTED
    PRIVATE
}

Java2Puml - PumlDoclet : > exécute le doclet
PumlDoclet - PumlDiagram : > génère le diagramme à l'aide de
PumlDiagram "1" - "*\n- classes" ClassContent : Stocke le contenu des classes\n >
PumlDiagram "1" -- "*\n- liaisons" Liaison : Stocke les liaisons entre les classes\n >
ClassContent "1" -- "*\n- classAttributs" Attribut : Liste les attributs de\n >
ClassContent "1" -- "*\n- classMethods" Methode : Liste les méthodes de\n >
Attribut "1" -- "1\n- visibilite" Visibilite : indique la visibilité\n >
Methode "1" -- "1\n- visibilite" Visibilite : indique la visibilité\n >
Liaison "1" - "2\n- element1\nelement2" ClassContent : Informe de la liaison entre\n >
Liaison "1" -- "1\n- typeLiaison" TypeLiaison : Indique le type de liaison\n >

@enduml